### ISSUE TITLE
Docs about Generic Views use deprecated urlpatterns syntax

### ISSUE THREAD

**Issue by guettli** [shtalinberg/django-el-pagination#10]
AFAIK the following code from the docs is deprecated.

```
urlpatterns = patterns('',
    (r'^publishers/$', ListView.as_view(model=Publisher)),
)
```

From http://django-el-pagination.readthedocs.org/en/latest/generic_views.html

New way: https://docs.djangoproject.com/en/1.9/topics/http/urls/#example

**Comment by shtalinberg** [comment]
Where there are specified so it is deprecated to do?
bellow I see similar example, just use the whole view import
https://docs.djangoproject.com/en/1.9/topics/http/urls/#id4

**Comment by guettli** [comment]
https://docs.djangoproject.com/en/1.9/ref/urls/#patterns

> Deprecated since version 1.8: urlpatterns should be a plain list of django.conf.urls.url() instances instead.

**Comment by shtalinberg** [comment]
Give an example of how you think it will be correct ? 
I can not understand that you do is deprecated

**Comment by guettli** [comment]
According to the docs from https://docs.djangoproject.com/en/1.9/ref/urls/#django.conf.urls.url

```
urlpatterns = [
    url(r'^index/$', index_view, name="main-view"),
    ...
]
```

**Comment by shtalinberg** [comment]
Ok, I add this information to next release.
Can you review my commit ?

**Comment by guettli** [comment]
I am too late for reviewing this. I looked at it. The support for Django 1.7 ended one year ago. I would not add notes about <1.8 in the docs.

The user would get errors messages which will get solved in seconds if you use your favourite search engine.

But the result looks good. Thank you.
