### ISSUE TITLE
'with' template tag

### ISSUE THREAD

**Issue by albardn2** [shtalinberg/django-el-pagination#105]
Hello,

django-el-pagination seems not to work when using {% with %} :
    {% with comments = post.comments.all %} 
    {% paginate comments %}
    {% for comment in comments %}
        #do something
.......
at the same time i cannot use post.comments.all with paginate.
can you please help me?

**Comment by SilmarillionUA** [comment]
Define 'comments' variable in your view and just use it in template without {% with %}.
