### ISSUE TITLE
Ability to add rel=nofollow per pagination

### ISSUE THREAD

**Issue by int-ua** [shtalinberg/django-el-pagination#109]
Or at least per view. I would like to add nofollow just to a subset of all paginations. Is it possible with current code?

**Comment by shtalinberg** [comment]
You can just copy el-pagination templates to project templates folder and modify as need

**Comment by int-ua** [comment]
It's how I have them already, but that's still a one global template for the whole project, isn't it?

**Comment by shtalinberg** [comment]
I merged pull-request from  @toptalo
