### ISSUE TITLE
I think Django 1.9 Does not need {{ block.super }} in twitter style pagination

### ISSUE THREAD

**Issue by ashishnetworks** [shtalinberg/django-el-pagination#11]
I was following documentation on readthedoc.org [[This Doc](http://django-el-pagination.readthedocs.org/en/latest/twitter_pagination.html)] where I followed following code for endless twitter style loading.

`
```

1. {% block js %}
2. {{ block.super }}
3. <script src="http://code.jquery.com/jquery-latest.js"></script>
4. <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
5. <script>
6. $.endlessPaginate({
7. paginateOnScroll: true,
8. paginateOnScrollChunkSize: 5});
9. </script>
10. {% endblock %}
```

`

But I always ended up getting Error:

> 'BlockNode' object has no attribute 'context'
 
but **removing {{ block.super }} solved my problem**.
I dont know whether behavior is same for Django < 1.9.

But still for 1.9 users I thought mentioning it here would be helpful

**Comment by shtalinberg** [comment]
1. {% block %}   -   block name is blank?
{{ block.super }}  - is necessary if you want to run block from the parent(extend) template

**Comment by ashishnetworks** [comment]
Hey thank you @shtalinberg for your reply.
{% block %} is not blank that was my typo its {% block js %}.  I just read https://goo.gl/7v8Do9 to comepltely understand meaning of {{ block.super }} in few lines. So I'm realizing now why I was getting that error, actually you know I was using {{ block.super }} without actually using extend in my templet.

[django-el-pagination's documentation](http://django-el-pagination.readthedocs.org/en/latest/twitter_pagination.html) is a bit confusing about this aspect because I think documenting team **Has Assumed** it that the page where {% include page_template %} is being written is extending some other base template and perhaps that is why they have used
{{ block.super }} inside {% block %} whereas in my case I was writing that {% block JS %} code in base template itself so obviously there was no need for me to use {{ block.super }}

This single assumption has created a little problem for many noobs like me. and caused many stackoverflow Questions like this http://goo.gl/6fCugV.

Well thanks anyway for such a wonderful app

**Comment by shtalinberg** [comment]
Big thanks @frankban :). I only provide support at the moment.

**Comment by ashishnetworks** [comment]
I am new for the django world but definitely not much stupid. I have gone through array of issues while creating my projects, so I would love to provide any support if I would be allowed to do so :)
