### ISSUE TITLE
Not working with 3.2.x

### ISSUE THREAD

**Issue by leench** [shtalinberg/django-el-pagination#119]
Django==1.11.13

when I update el-pagination to 3.2.4, page shows:
 ```
<el_pagination.models.ELPage object at 0x7f88c1c3c090> <el_pagination.models.ELPage object at 0x7f88c2137450> <el_pagination.models.ELPage object at 0x7f88c1c3c090>
```
template is:
```
          {% get_pages %}
          <div class="page">
            <div class="pagination">
              {{ pages.first_as_arrow }}
              {{ pages.previous }}
               {{ pages.current }} 
              {{ pages.next }}
            </div>
          </div>
```

3.1.0 works fine. I tested 3.2.1 and 3.2.4.

**Comment by vparitskiy** [comment]
Are you sure that you did not override `show_pages.html` with your own template?

I had the same issue and occasionally now it uses `{{ page.render_link }}` instead of just `{{ page }}` in `show_pages.html`  template

**Comment by IanLawrence** [comment]
Hit by this too

**Comment by dennnis0204** [comment]
I have the same problem, how did you solve it ?
```
<div class="pagination">
    {% get_pages %}
    {{ pages.current }}
</div>
```
```
<el_pagination.models.ELPage object at 0x7f90da57c0b8>
```
django==1.11.16
django-el-pagination==3.2.4

**Comment by justin76tan** [comment]
3.2.4. is working, I test.
