### ISSUE TITLE
Too many pages are generated for search indexes

### ISSUE THREAD

**Issue by int-ua** [shtalinberg/django-el-pagination#121]
Right now when there are two paginations on a page with N and M elements it generates N*M pages for search indexes. While it would be enough with just N+M total pages if paginations did not include other paginations' keys.

For now I've change href in `page_link.html` template to `?{{ page.querystring_key }}={{ page.number }}` but that relies on the fact that I don't use any other GET parameters anywhere where I use `el_pagination`.

**Comment by shtalinberg** [comment]
Just add Disallow: /*?page=*  to robots.txt

**Comment by int-ua** [comment]
Well, that's also a way to do it, of course. Ok, I'll close that for now.

**Comment by int-ua** [comment]
New info: workaround that I used before breaks using `django-filter`, of course. Another obvious way is to move paginations to separate pages and looks like I'll have to do this.
