### ISSUE TITLE
Multiple pagination on the same page

### ISSUE THREAD

**Issue by Julio0025** [shtalinberg/django-el-pagination#122]
My goal is to have multiple paginations on the same page in different tabs. Single tab pagination works fine. I'm following multiple page implementation [documentation](http://django-endless-pagination.readthedocs.io/en/latest/multiple_pagination.html) and i'm having no success. One of the first errors i got was: **'WSGIRequest' object has no attribute 'REQUEST'**. After some digging around in the source code i found some deprecated methods. Like using **'request.REQUEST.get()'** instead of **'request.GET()'**. Also documentation example uses argument **context_instance=RequestContext(request)** witch was also removed in django 1.10. I'm using django 1.11 with django-el-pagination-3.2.4. Is the documentation for this particular case not updated or am i doing something wrong. My code is exactly the same as in the example given.

**Comment by BertrandBordage** [comment]
I noted that this regression occurred between 3.2.2 and 3.2.3.

**Comment by int-ua** [comment]
The link is to an old projects` docs and this is a fork, check https://django-el-pagination.readthedocs.io/en/latest/multiple_pagination.html
Also, looks like it needs `render()` instead of `render_to_response()`

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)

**Comment by shtalinberg** [comment]
also you can see test project as example multiple pagination
