### ISSUE TITLE
Android Chrome Issue

### ISSUE THREAD

**Issue by willslater** [shtalinberg/django-el-pagination#126]
I have been using the plugin for some time and in the main it works great but came across a strange bug. It doesn't seem to like Android chrome browser, all other browsers seem to work even Chrome for iOS, however on Android chrome it doesn't work with no errors via remote debugging. 

I say it doesn't work, it actually does but only if I close chrome then re open, then it works once, close again, open and works once and so on. 

I am using auto loading (reach bottom of the page and load more), and it does actually fall back on button press loading, but it really stops the flow of the site to use that. 

Has anybody got / had similar issue and worked out the issue? Basically doesn't trigger load more on scroll, but only Android chrome. It's hard to debug with no errors. 

Python: 2.7
Django: 1.9.2
django-el-pagination: 3.1.0

**Comment by shtalinberg** [comment]
what Android version ? 
what chrome version ? 
did you try latest stable el-pagination version?
