### ISSUE TITLE
Minor release to fix the prints?

### ISSUE THREAD

**Issue by yurkobb** [shtalinberg/django-el-pagination#128]
Hi and first of all thanks for the package.

Now, I was curious about these `get_rendered` popping up on stdout in the middle of my `./manage.py test` runs and then I found it [was fixed](https://github.com/shtalinberg/django-el-pagination/commit/b2ea6948f1b1711b31fe118bba36004873ddc141), but not yet released. I think even for small yet meaningful changes like this, doing a minor release would be great.

**Comment by shtalinberg** [comment]
try 3.3.0
