### ISSUE TITLE
Is Endless pagination really not SEO friendly ?

### ISSUE THREAD

**Issue by ashishnetworks** [shtalinberg/django-el-pagination#13]
I have heard and read in many places that endless pagination or anything where contents are loaded using AJAX is not SEO friendly or at least not so easily. In Contrast while using this app I never came to write anything much in javascript. It just simply loads content dynamically using include tag of template isn't?. But yet somehow I was wondering even this app must be using Ajax in background so is it really not SEO friendly to use this app for endlessly loading content using twitter style pagination ?

**Comment by shtalinberg** [comment]
for better SEO-friendly you may use sitemap.xmp and detail pages.

**Comment by ashishnetworks** [comment]
did you mean sitemap.XML ? or was it really xmP ? I'm considering it typo

**Comment by shtalinberg** [comment]
Yes it typo, now fixed.

**Comment by shtalinberg** [comment]
Close this Issue ?
