### ISSUE TITLE
Error importing python_2_unicode_compatible in Django 3

### ISSUE THREAD

**Issue by DanielSwain** [shtalinberg/django-el-pagination#136]
Trying to run in Django 3 resulted in:

```
File "/venv/lib/python3.6/site-packages/el_pagination/models.py", line 8, in <module>
    from django.utils.encoding import iri_to_uri, python_2_unicode_compatible, force_text
ImportError: cannot import name 'python_2_unicode_compatible'
```

`python_2_unicode_compatible` is [no longer available in Django](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis)

**Comment by koloyyee** [comment]
I also want to know how to fix the problem

**Comment by angyangcheng** [comment]
Any idea how to fix this issue?

**Comment by q-user** [comment]
Please review PR #137

**Comment by shtalinberg** [comment]
merged
