### ISSUE TITLE
New release of django-el-pagination compliant with django2.2

### ISSUE THREAD

**Issue by moumoutte** [shtalinberg/django-el-pagination#139]
Hi!

Can you provide please a new release of django-el-pagination on pypi ? The last release available is dated from February the 1st 2018. Since django2.2 will become soon the new LTS version, We need to update the package with your last commits!

Many thxs!

**Comment by shtalinberg** [comment]
release in progress
we want add support Django 2.2 and 3.0.x 
at the moment I will do changes for success testing on the Travis CI and will make release

**Comment by joehybird** [comment]
Job done. A release please :smile:

**Comment by shtalinberg** [comment]
will do it tomorrow

**Comment by joehybird** [comment]
Thx :+1:

**Comment by shtalinberg** [comment]
sorry for waiting 
3.3.0 released
