### ISSUE TITLE
Latest release (3.3.0) still contains force_text

### ISSUE THREAD

**Issue by andrewmackie** [shtalinberg/django-el-pagination#154]
Django 4.0 has removed django.utils.encoding.force_text.

@FuzzyGrim replaced force_text with force_str in development but this hasn't made it into a release yet (release 3.3.0 still contains force_text).

Can you please create a new release which incorporates this change?

**Comment by DanielSwain** [comment]
I need this too please.

**Comment by shu-ha-ri** [comment]
bump! changes are already there, just need them released please.

**Comment by hockeymikey** [comment]
Can we get an upgrade? Ran into this too and the changes are there.

**Comment by cclauss** [comment]
Fixed in #153?

**Comment by Semprini** [comment]
Please release me, can't you see
You'd be a fool to cling to me
So release me and let me love again
Let me love, let me go
 - #153 & Engelbert Humperdunk

**Comment by benmcnelly** [comment]
Is this released yet?

**Comment by cclauss** [comment]
Releases are https://github.com/shtalinberg/django-el-pagination/tags

**Comment by shtalinberg** [comment]
Hi, guys!
I had to put aside support for open source projects for a while
Sorry for waiting release, we have a war in my country  :-(
I will review everything and make a release by the end of this week

**Comment by cclauss** [comment]
Yes.  We thought so.  Glad to hear that you are safe.

We wish Ukraine 🇺🇦 a rapid and complete victory over the aggressors.

**Comment by cclauss** [comment]
Gentle bump on getting a release out...

**Comment by cclauss** [comment]
@shtalinberg Gentle bump on getting a release out... Hopefully with the changes in https://github.com/shtalinberg/django-el-pagination/pull/161 included.

**Comment by shtalinberg** [comment]
Bumped version 4.0.0

Sorry for waiting.
