### ISSUE TITLE
Release v4.1.0 to PyPI for support of Django v5.0 and Python 3.12

### ISSUE THREAD

**Issue by cclauss** [shtalinberg/django-el-pagination#170]
https://github.com/shtalinberg/django-el-pagination/blob/develop/README.rst
> From version 4.1.0 added support Django 5.0 and Python 3.12
---
Current release on PyPI is 4.0.0:
https://pypi.org/project/django-el-pagination/ supports Django <= v4.1
* https://github.com/shtalinberg/django-el-pagination/releases
---
* https://github.com/shtalinberg/django-el-pagination/pull/168 -- Merged but not yet released to PyPI.

**Comment by shtalinberg** [comment]
4.1.0 released
