### ISSUE TITLE
'el_pagination_tags' is not a registered tag library. After update to 4.1.1

### ISSUE THREAD

**Issue by nick-romano-onlogic** [shtalinberg/django-el-pagination#175]
Hello, thank you for maintaining this plugin!

Unfortunately after updating from 4.0.0 to 4.1.X I'm encountering the following error when loading any page with a tempalte that includes `el_pagination_tags`.

`'el_pagination_tags' is not a registered tag library.`

Reverting to 4.0.0 solves this problem. 

I did a brief peak through the code changes, and it seems like most of the changes from 4.0.X to 4.1.X are build process related. Should I be loading el pagination differently? 

Please let me know if there is any additional information you need.

------

I'm using Django 5.1.3 with python:3.11.10

Context processors look like:

```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "DIRS": [],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "onlogic_core_ui.context_processors.onlogic_ui_theme",
                "django.template.context_processors.media",
            ],
        },
    },
]
```

'el_pagination' is included in installed apps.

**Comment by shtalinberg** [comment]
Compatible with Django 5.1 will be released as 4.2 version in a few days

**Comment by micmarc** [comment]
I'm having the same issue with 4.1.1 on Django 4.2 / Python 3.10.

**Comment by shtalinberg** [comment]
django-el-pagination 4.1.2  released,  It should fix that

**Comment by nick-romano-onlogic** [comment]
Thank you so much for investigating and updating! I will test this out today.

**Comment by alexandrenorman** [comment]
It works for me ! Thanks for the fix !

**Comment by nick-romano-onlogic** [comment]
Works for me as well! Thanks again. I will close out this issue.
