### ISSUE TITLE
Integrate <link> tags in <head> for SEO

### ISSUE THREAD

**Issue by sebastien247** [shtalinberg/django-el-pagination#23]
Hi,
How to integrate `<link>` tags in `<head>` for SEO ?

Example for current page = 4 :
```
<head>
    <link rel="prev" href="?page=3" />
    <link rel="canonical" href="?page=4" />
    <link rel="next" href="?page=5" />
</head>
```

Thanks and sorry for my english

**Comment by shtalinberg** [comment]
it's not pagination task, but you can create separate template tag for this future and make pull-request

see in settings.py:
```
# The querystring key of the page number.
PAGE_LABEL = getattr(settings, 'EL_PAGINATION_PAGE_LABEL', 'page')
```

**Comment by sebastien247** [comment]
Ok thank, but how to know if there is a next or previous page?

**Comment by cyriac** [comment]
Pagination object has methods that tell you if the current page has previous or next pages.
ref: https://docs.djangoproject.com/en/1.8/topics/pagination/#example

For the el-pagination package inside your templates the methods can be accessed as below.
```{{ endless.page.has_previous }}```
```{{ endless.page.has_next }}```

ref: https://github.com/shtalinberg/django-el-pagination/blob/develop/el_pagination/templatetags/el_pagination_tags.py#L319

**Comment by sebastien247** [comment]
Ok, thank. But is impossible to create link tag with include for this reason :

> The include tag should be considered as an implementation of “render this subtemplate and include the HTML”, not as “parse this subtemplate and include its contents as if it were part of the parent”. This means that there is no shared state between included templates – each include is a completely independent rendering process.
> 
> Blocks are evaluated before they are included. This means that a template that includes blocks from another will contain blocks that have already been evaluated and rendered - not blocks that can be overridden by, for example, an extending template.

https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#include

**Comment by cyriac** [comment]
That sounds like something you will have to solve in your project by re-arranging your template inheritance. It is not something django-el-pagination can solve.
