### ISSUE TITLE
Docs looking outdated

### ISSUE THREAD

**Issue by guettli** [shtalinberg/django-el-pagination#26]
> See Generic views if you use Django >= 1.3 and you want to replicate the same behavior using a 
> class-based generic view.

From: http://django-el-pagination.readthedocs.io/en/latest/twitter_pagination.html

Today the latest version is Django 1.9.5.

Most people use class-based-views today.

What do you think?

**Comment by shtalinberg** [comment]
Can you help fix it and make pull-request ?

**Comment by guettli** [comment]
Thank you!
