### ISSUE TITLE
Docs: entry_index.html vs entry_list.html

### ISSUE THREAD

**Issue by guettli** [shtalinberg/django-el-pagination#29]
You use the template name "myapp/entry_index.html"

Example: http://django-el-pagination.readthedocs.io/en/latest/twitter_pagination.html

The django docs use "myapp/entry_list.html"

Example: https://docs.djangoproject.com/en/1.9/ref/class-based-views/generic-display/#listview

It would be kind if you could follow the django naming conventions. This would make it more easy for new comers.

**entry_index.html vs entry_list.html**

What do you think?

**Comment by shtalinberg** [comment]
I think for new comers it would be better if they will understand that it is not necessarily all follow these rules

**Comment by guettli** [comment]
I love it, if things can be done in "no-brainer" mode. Every bit that irritates slows down. But you are right. On the other hand I like this: https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds ... You are the maintainer and I wanted to let you know what I think. It's ok if you don't care.

**Comment by shtalinberg** [comment]
I change it in 3.0.0
