### ISSUE TITLE
Keep old application name

### ISSUE THREAD

**Issue by jungornti** [shtalinberg/django-el-pagination#3]
Hello, there.

It is good idea to keep old app name `endless_pagination`, because anyone can upgrade smoothly, to your version of endless_pagination. Just keep in mind what the "Pillow" guys did with the project name and structure.

**Comment by shtalinberg** [comment]
django-el-pagination will develop independently of endless_pagination to avoid conflicts.
Now just need to update the application to rename el_pagination in INSTALLED_APPS, 
folder templates/endless to templates/el_pagination if you copy,
and rename load templatetags {% load endless %}  to {% load el_pagination %}. 
And yet - the application will run as html-marking and scripts have not changed now

**Comment by jungornti** [comment]
Okay, but nobody will use endless_pagination and your library together, because of pagination consistency. So, it is pointless to force users make refactoring to ALL their templates with pagination, you can provide transparent upgrade from the start of library development.

You can keep the package name as el_pagination alongside with old application name.

**Comment by andreav** [comment]
I also had to change this:

```
-<script src="{% static 'endless_pagination/js/endless-pagination.js' %}"></script>
+<script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>

```

**Comment by jungornti** [comment]
Thats why the library should be named after ``endless_pagniation``, to ease migration.
``Pil`` and ``Pillow``, ``django-ckeditor`` and ``django-ckeditor-updated`` are nice examples of such application naming.

**Comment by shtalinberg** [comment]
@andreav
In what place did you find?


@jungornti 
Yes, maybe you were right about the name.
But Today:
1. I consider the likelihood that the author will return to the original application. I renamed so that people are not confused. So they know exactly which of the applications they have installed.
2. I need a lot to return back. I find it easier to support a new application.

IMHO not so much to change in the code as for me during the transition.
I have myself spent on it as much as much as 15-30 minutes, using search in the console.

**Comment by andreav** [comment]
Inside my templates, when I include el-pagination.js in order to call $.endlessPaginate

**Comment by jungornti** [comment]
@shtalinberg sure, it is your descision, i'm not forcing you to rename the library =)

But you can think about it like so: users should be refactoring their templates every time they want to switch to your library or back, spending their time (spending time = low motivation), but you can do that just one time.

**Comment by alb3rto269** [comment]
Maybe you can write an upgrade guide. I needed to search in closed issues and read your commits to have a clue of what should be changed.
