### ISSUE TITLE
Docs: Please provide sample templates for class based views

### ISSUE THREAD

**Issue by guettli** [shtalinberg/django-el-pagination#30]
Please provide sample templates for class based views

Here: http://django-el-pagination.readthedocs.io/en/latest/generic_views.html#el_pagination.views.AjaxListView.page_template

Thank you

**Comment by ArtemBernatskyy** [comment]
Agree.

**Comment by shtalinberg** [comment]
exactly what you need to show to make it clear?

**Comment by ArtemBernatskyy** [comment]
Provide plz full example of both CBV and FBV for newcomers, i will be very thankfull for CBV specially. I mean real working application which uses `django-el-pagination` . You know it will be very practical to keep such things in github repository for example.

**Comment by shtalinberg** [comment]
Reopen the ticket if not it enough that I added in 3.0.0

**Comment by ArtemBernatskyy** [comment]
Thanks a lot, haven't tested it yet, but looks good. It will save some time for newcomers)
