### ISSUE TITLE
Encountered unknown tag 'load'

### ISSUE THREAD

**Issue by kodeine** [shtalinberg/django-el-pagination#31]
i am getting this error on template file, `django.template.base.TemplateSyntaxError
TemplateSyntaxError: ("Encountered unknown tag 'load'.",)`

```python
{% load el_pagination_tags %}

{% paginate entries %}
{% for entry in entries %}
     your code to show the entry
{% endfor %}
{% show_more %}
```

Can you please let me know what is wrong.

**Comment by shtalinberg** [comment]
check settings for template loader
