### ISSUE TITLE
TypeError: decorated() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by MrTimscampi** [shtalinberg/django-el-pagination#35]
Following [Digg-style pagination > Adding Ajax](http://django-el-pagination.readthedocs.io/en/latest/digg_pagination.html#adding-ajax), I get this:

```
url(r'^$', views.list_files(), name='list-files'),
TypeError: decorated() missing 1 required positional argument: 'request'
```

I'm using Django 1.9.7.

Url is defined like this: `url(r'^$', views.list_files(), name='list-files'),`  
The rest is basically copy-pasted from the doc, with function name changed.

**Comment by LeeKyungMoon** [comment]
Did you solve this problem?

**Comment by shtalinberg** [comment]
views.list_files()   -   decorated ?
you can show my more code ? list_files view for example

**Comment by LeeKyungMoon** [comment]
remove '()' after 'view.list_files'
