### ISSUE TITLE
Broken in Django 1.10 by missing private variable 

### ISSUE THREAD

**Issue by liamuk** [shtalinberg/django-el-pagination#37]
The private variable `Paginator._num_pages`, which el-pagination relies on is removed in this commit https://github.com/django/django/commit/79a091820f46f00cba217a9e05daec855272c3ad.
 
Easy fix would be to add `self._num_pages = None` to `BasePaginator.__init__`

**Comment by shtalinberg** [comment]
After success build on TravisCI 3.0.0  will be released
