### ISSUE TITLE
Bootstrap 4 support.

### ISSUE THREAD

**Issue by tutuca** [shtalinberg/django-el-pagination#46]
There is some pressure to release the fourth version of Bootstrap [1].

Are there plans to update crispy forms template to match?
Is there some current effort ongoing?

[1]http://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/

**Comment by shtalinberg** [comment]
django-el-pagination  don't use crispy forms template

**Comment by tutuca** [comment]
So much for reporting bugs at 2 am... Used the wrong tab. Sorry!
