### ISSUE TITLE
Add  {% paginate latest_article_list %}  after an error

### ISSUE THREAD

**Issue by liwei01** [shtalinberg/django-el-pagination#47]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 1.9.9
Python Version: 2.7.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'xadmin',
 'crispy_forms',
 'reversion',
 'userena',
 'guardian',
 'easy_thumbnails',
 'django.contrib.sites',
 'el_pagination',
 'pure_pagination',
 'myapp']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Template error:
In template D:\www\CMS\mycms\myapp\templates\index.html, error at line 4
   request   1 : <html>
   2 : {% load el_pagination_tags %}
   3 : 
   4 :  {% paginate latest_article_list %} 
   5 : {% for article in latest_article_list %}
   6 :     {# your code to show the entry #}
   7 :     <div class="dz-list-con">
   8 :         <a id="article_title", href=/focus/{{ .id }}>
   9 :           <p style="font-weight: bold;">{{ article.title }}</p>
   10 :         </a>
   11 :         <p>{{ article.content|truncatechars_html:80 | safe }}</p>
   12 :     </div>
   13 : {% endfor %}
   14 : {% show_pages %}

Traceback:

File "D:\www\CMS\django1.9\lib\site-packages\django\core\handlers\base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "D:\www\CMS\django1.9\lib\site-packages\django\core\handlers\base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "D:\www\CMS\mycms\myapp\views.py" in index

File "D:\www\CMS\django1.9\lib\site-packages\django\shortcuts.py" in render_to_response
  39.         content = loader.render_to_string(template_name, context, using=using)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\loader.py" in render_to_string
  97.         return template.render(context, request)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\backends\django.py" in render
  95.             return self.template.render(context)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\base.py" in render
  206.                     return self._render(context)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\base.py" in _render
  197.         return self.nodelist.render(context)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\base.py" in render
  992.                 bit = node.render_annotated(context)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\base.py" in render_annotated
  959.             return self.render(context)

File "D:\www\CMS\django1.9\lib\site-packages\el_pagination\templatetags\el_pagination_tags.py" in render
  307.             context['request'], querystring_key, default=default_number)

File "D:\www\CMS\django1.9\lib\site-packages\django\template\context.py" in __getitem__
  77.         raise KeyError(key)

Exception Type: KeyError at /
Exception Value: u'request'

**Comment by shtalinberg** [comment]
which version of the el_pagination  you are using?

**Comment by liwei01** [comment]
django1.9.9   
el_pagination  is   pip install      The latest version
There is a problem, it won't, now use Paginator

**Comment by shtalinberg** [comment]
please run 
`pip freeze | grep 'el-pagination'`

**Comment by liwei01** [comment]
pip lfreeze| grep 'el-pagination'
django-el-pagination==3.0.1


λ pip freeze
Django==1.9.9
django-crispy-forms==1.6.0
django-el-pagination==3.0.1
django-formtools==1.0
django-guardian==1.4.1
django-reversion==2.0.6
django-userena==2.0.1
django-xadmin==0.5.0
easy-thumbnails==2.3
html2text==2014.12.29
httplib2==0.9.2
markdown2==2.3.1
MySQL-python==1.2.3
Pillow==3.3.1
six==1.10.0
xadmin==0.6.1

**Comment by shtalinberg** [comment]
Do you have request context processor in your settings.py ? 
e.g.:
```
from django.conf.global_settings import TEMPLATES
TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')

```

**Comment by liwei01** [comment]
http://django-el-pagination.readthedocs.io/en/latest/start.html#settings
I was refer to the above instructions, do not know right, add after, as follows

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.core.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

**Comment by liwei01** [comment]
I just tried again, or an error  “u'request'”  ， as follows：

KeyError at /myapp/test/
u'request'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/myapp/test/
Django Version:	1.9.9
Exception Type:	KeyError
Exception Value:	
u'request'
Exception Location:	D:\www\CMS\django1.9\lib\site-packages\django\template\context.py in __getitem__, line 77
Python Executable:	D:\www\CMS\django1.9\Scripts\python.exe
Python Version:	2.7.12
Python Path:	
['D:\\www\\CMS\\mycms',
 'D:\\www\\env\\django_env\\Scripts',
 'C:\\Windows\\system32\\python27.zip',
 'D:\\www\\CMS\\django1.9\\DLLs',
 'D:\\www\\CMS\\django1.9\\lib',
 'D:\\www\\CMS\\django1.9\\lib\\plat-win',
 'D:\\www\\CMS\\django1.9\\lib\\lib-tk',
 'D:\\www\\CMS\\django1.9\\Scripts',
 'c:\\python27\\Lib',
 'c:\\python27\\DLLs',
 'c:\\python27\\Lib\\lib-tk',
 'D:\\www\\CMS\\django1.9',
 'D:\\www\\CMS\\django1.9\\lib\\site-packages']
Server time:	星期四, 15 九月 2016 23:27:55 +0800


Error during template rendering

In template D:\www\CMS\mycms\myapp\templates\test.html, error at line 9
request
1	{% extends "common/base.html" %}
2	
3	{% block nav %}
4	  {% include "common/nav.html" %}
5	{% endblock %}
6	
7	{% block main %}
8	        {% load el_pagination_tags %}
9	        {% paginate latest_article_list %}
10	        {% for article in latest_article_list %}
11	        
12	            <div class="media well">
13	                <div class="dzlist-top">
14	                <div class="dz-username"><a href="/users/1/" rel="nofollow">{{ article.author }}</a>
15	                    <span>{{ article.update_time }}</span></div>
16	                </div>
17	                <div class="dz-list-con">
18	                    <a id="article_title", href=/myapp/{{ article.id }}>
19	                    <p style="font-weight: bold;">{{ article.title }}</p>

**Comment by shtalinberg** [comment]
Please show       
File "D:\www\CMS\mycms\myapp\views.py" in index

**Comment by liwei01** [comment]
Below this, 'def index (request)' directly with Paginator paging is normal
'def test (Request)' with el - pagination is an error

==================
#coding=utf=8
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.views.decorators.cache import cache_page
from django.template import RequestContext
import markdown2, urlparse
#分页用
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):  
    article_list = Article.object.query_by_time()
    #分页 开始
    paginator = Paginator(article_list, 5) #查询出来的数据传到分页， 第二个是每页面显示的数量
    page = request.GET.get('page')
    try:
        latest_article_list = paginator.page(page)
    except PageNotAnInteger:
        latest_article_list = paginator.page(1)
    except EmptyPage:
        latest_article_list = paginator.page(paginator.num_pages)
    #分页 完

    #右边 热门段子精选 10个
    Pulls = Pulls_index()
    #右边 图片1个
    Img1 = Img.objects.all()[0:2]

    context = {'latest_article_list': latest_article_list, 'Pulls':Pulls, 'Img1':Img1 }
    return render_to_response('index.html',context)

def test(Request):
    article_list = Article.object.query_by_time()
    context = {'latest_article_list': article_list }
    return render_to_response('test.html',context)

def article(request, article_id):
    article = get_object_or_404(Article, id=article_id)   
    return render(request, 'article_page.html',{'article': article})


#右边 热门段子精选 10个
def Pulls_index():
    Pulls = Article.object.query_by_polls()[0:10]
    return Pulls

#动图
def gif_index(request):
    Imgs = Img.objects.all()


    #右边 热门段子精选 10个
    Pulls = Pulls_index()
    #右边 图片1个
    Img1 = Img.objects.all()[0:2]

    contact = {'Imgs':Imgs, 'Pulls':Pulls, 'Img1':Img1}
    return render_to_response('common2/gif.html', contact, context_instance=RequestContext(request))

@login_required
def comment(request, article_id):
    form  = CommmentForm(request.POST)
    url = urlparse.urljoin('/focus/', article_id)
    if form.is_valid():
        user = request.user
        article = Article.object.get(id=article_id)
        new_comment = form.cleaned_data['comment']
        c = Comment(content=new_comment, article_id=article_id)  # have tested by shell
        c.user = user
        c.save()
        article.comment_num += 1
    return redirect(url)

@login_required
def get_keep(request, article_id):
    logged_user = request.user
    article = Article.object.get(id=article_id)
    articles = logged_user.article_set.all()
    if article not in articles:
        article.user.add(logged_user)  # for m2m linking, have tested by shell
        article.keep_num += 1
        article.save()

        return redirect('/focus/')
    else:
        url = urlparse.urljoin('/focus/', article_id)
        return redirect(url)

@login_required
def get_poll_article(request,article_id):
    logged_user = request.user
    article = Article.object.get(id=article_id)

    #polls = logged_user.poll_set.all()
    polls = logged_user
    articles = []
    for poll in polls:
        articles.append(poll.article)

    if article in articles:
        url = urlparse.urljoin('/focus/', article_id)
        return redirect(url)
    else:
        article.poll_num += 1
        article.save()
        poll = Poll(user=logged_user, article=article)
        poll.save()
        data = {}
        return redirect('/focus/')

**Comment by shtalinberg** [comment]
Please show
File "D:\www\CMS\mycms\myapp\views.py" in index
only version with error in el_pagination

**Comment by liwei01** [comment]
I don't know where is wrong?
Can give a 'views.py' example?

I'm empty now 'views.py'
Only the following:
#coding=utf=8
from django.shortcuts import render, redirect, render_to_response
from .models import *

def test(request):
    article_list = Article.object.query_by_time()
    context = {'latest_article_list': article_list }
    return render_to_response('test.html',context)

 
Is still the same error

**Comment by shtalinberg** [comment]
You should use context=RequestContext(request, my_context)  
context = RequestContext(request, {'latest_article_list': article_list })   for example ... 

See example in doc http://django-el-pagination.readthedocs.io/en/latest/twitter_pagination.html

**Comment by liwei01** [comment]
Thank you very much!
With the help of you, I find the reason for the error.
Is that all right now
