### ISSUE TITLE
AjaxListView support multiple paginations in the same page?

### ISSUE THREAD

**Issue by adriancarayol** [shtalinberg/django-el-pagination#51]
**AjaxListView** can support multiple paginations in the same page? I see doc (http://django-el-pagination.readthedocs.io/en/latest/multiple_pagination.html), but AjaxListView says nothing, only it appears for function.

I try with:
 `class Foo(AjaxListView):
      page_template = 'foo.html, foo2.html'
`
and
 `class Foo(AjaxListView):
      page_templates = 'foo.html, foo2.html'
`
Thanks.

**Comment by shtalinberg** [comment]
AjaxListView should support.
Need to try and add example to documentation

**Comment by adriancarayol** [comment]
Sure, but I can't find :-P.

 Good fork!

Thanks.

**Comment by tsotnesharvadze** [comment]
how to fix?

**Comment by int-ua** [comment]
Looks like template names are hardcoded in case of `AjaxListView` and key is not used, so doesn't look like multiple templates and, in consequence, multiple paginations are supported:
https://github.com/shtalinberg/django-el-pagination/blob/99de42e47f5bf1a021e4b46f4efbb476f8ff2684/el_pagination/views.py#L142
```
        return '{0}/{1}{2}{3}.html'.format(
            opts.app_label,
            opts.object_name.lower(),
            self.template_name_suffix,
            self.page_template_suffix,
)
```

**Comment by shtalinberg** [comment]
it should works as described in   documentation
