### ISSUE TITLE
Error : IndexError: list index out of range

### ISSUE THREAD

**Issue by valerioorfano** [shtalinberg/django-el-pagination#54]
Hi All,

i ve installed django-el-pagination on my anaconda env. Installation is successful but when i insert the row:
IndexError: TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context')

i get the error in the subject:  IndexError: list index out of range.

I've python 3.5 and relative last Django version.

Could you please help me out?

Thanx valerio

**Comment by valerioorfano** [comment]
Sorry i meant when i insert the row on my settings.py:
TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context')

i get the error: IndexError: list index out of range

Any idea whee the error is?
I've python 3.5 and relative last Django version.

thx valerio

**Comment by shtalinberg** [comment]
Maybe you typo ? need
`
TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')`

**Comment by valerioorfano** [comment]
You’ re right sorry, I’m using a different language keyboard right now :)

When i insert


TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')

in my settings.py i get the "IndexError: list index out of range"

If i remove the row above from my settings i get an error during the statement:
{% include page_template %} Missing authorisation to access page_template
I don’t know if these two things are related.
I’ve followed the instructions from the documentation you posted on github.
Any clue?

Rgds valerio






On 15 Nov 2016, at 19:35, Oleksandr <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe you typo ? need

TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')

**Comment by shtalinberg** [comment]
You can show you settings.py ?

**Comment by valerioorfano** [comment]
Hi Oleks


here you get my settings.py

...................................


import os

from django.conf.global_settings import TEMPLATES
TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(wjf)^a40mzvwj#8^zl!^evs8i@2#dzv)#)!qcav+s$us+2ylz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patentdb.apps.patentdbConfig',
    'widget_tweaks',
    'haystack',
    'el_pagination',
]

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
        'URL': 'http://127.0.0.1:9200/',
        'INDEX_NAME': 'mise',
    },
}

MEDIA_ROOT = "C:/Users/uibm/workspace/ES_Brevetti/media"
MEDIA_URL = "media/"



MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ES_Brevetti.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ES_Brevetti.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = '/home/dan/mysite/media/'

MEDIA_URL = '/media/'



________________________________

**Comment by valerioorfano** [comment]
Hi Oleks this issue has been fixed the the following settings:


I am using Django 1.9.6



from django.conf.global_settings import TEMPLATES

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [os.path.join(BASE_DIR, 'templates')],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.core.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
}]






________________________________

**Comment by shtalinberg** [comment]
if you have 'django.template.context_processors.request',   then  'django.core.context_processors.request' don't need. you can remove it's dublicate

**Comment by valerioorfano** [comment]
Ok thx

Regards Valerio

Il giorno 16/nov/2016, alle ore 11:10, "Oleksandr" <notifications@github.com<mailto:notifications@github.com>> ha scritto:


if you have 'django.template.context_processors.request', then 'django.core.context_processors.request' don't need. you can remove it's dublicate

-
