### ISSUE TITLE
Paginating on scroll is not working

### ISSUE THREAD

**Issue by valerioorfano** [shtalinberg/django-el-pagination#55]
Hi Oleks, I m testing the paginating on scroll but it's not working as i expect.

As per documentation:
I've added the following in my main page ricerca.html

........
<div class="endless_page_template">
        {% include page_template %}
</div>

{% block js %}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
     <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 20
        });
    </script>
{% endblock %}
</body></html>
{% endautoescape %}

I've removed  from my sub_ricerca.html that is my page_template

{% load el_pagination_tags %}
{% paginate entry_list %}
{% for entry in entry_list %}
    {# mycode to show the entry #}
{% endfor %}
{% show_more %}

But all the results are returned the first time i submit the form, and not "page on scroll" is executed.

**Comment by valerioorfano** [comment]
I've also tried with this but still not working :
......
<div class="endless_page_template">
{% include page_template %}
</div>

{% block js %}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
     <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 20
        });
    </script>
{% endblock %}

</body></html>
{% endautoescape %}

**Comment by valerioorfano** [comment]
This is my view:
.......
    template='ricerca.html'
    page_template = 'sub_ricerca.html'
    context = {
        'entry_list': context_all,
        'page_template': page_template
    }
    if request.is_ajax():
        template = page_template
    return render_to_response(template, context, context_instance=RequestContext(request))

**Comment by shtalinberg** [comment]
Hi valerioorfano
I think it's not bug. Try read documentation and try examples.  
It's app work on production with Paginating on scroll without any problem.
You need more experience with django app or try hire experienced developer.
