### ISSUE TITLE
{% paginate 5 entries with "/ajax/data/" %}, didn't refer to "/ajax/data/" url.

### ISSUE THREAD

**Issue by thinking0** [shtalinberg/django-el-pagination#56]
Hi.
Can I change my ajax api url to as "/ajax/data/"? hopefully, change it like fixed.
as I typed above, I would like to get some data from "/ajax/data/" url. but there was not happened.

could you let me know how can I solve this?

**Comment by shtalinberg** [comment]
it's wrong...
for ajax read  http://django-el-pagination.readthedocs.io/en/latest/twitter_pagination.html#twitter-page-template

**Comment by thinking0** [comment]
there was no way to freezes url like that? already applied ajax logic..  it was fine. but my purpose is that getting data from other url. for instance, at /hello/ page, load some data from /noti/ url by el-pagination. 
is it same solution what you answered me?

**Comment by shtalinberg** [comment]
Yes, you can try same solution - just load right response data and template in /ajax/data/  view

**Comment by thinking0** [comment]
thanks shtalinberg. i'll try it
