### ISSUE TITLE
Generated rel="page" is an error in html5 validator

### ISSUE THREAD

**Issue by int-ua** [shtalinberg/django-el-pagination#59]
The text being

```
Bad value page for attribute rel on element a: The string page is not a registered keyword.

<a href="?page=2"↩    rel="page"↩    class="endless_page_link">2</a>
```
Syntax of list of link-type keywords:
A whitespace-separated list of link types, with no duplicate keywords in the list.
Each link type must be listed as allowed on <a> and <area> in the [HTML specification](https://html.spec.whatwg.org/multipage/links.html#linkTypes),
or must be listed as allowed on <a> and <area> on the [Microformats wiki](http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions).
You can register link types on the Microformats wiki yourself.

I'm using a local version with [html5validator](https://github.com/svenkreiss/html5validator) but it can also be checked on http://validator.w3.org/

`django-el-pagination==2.1.1`

**Comment by shtalinberg** [comment]
You can copy template and make own version for your site

**Comment by int-ua** [comment]
Is it some proposed `rel` type that wasn't accepted yet? Do you really want to stick with it or will you accept a pull request that converts it to `data-querystring-key`?

**Comment by shtalinberg** [comment]
yes, I will accept a pull request that converts it to data-querystring-key

**Comment by shtalinberg** [comment]
for release 3.1.0
I replace link attribute rel="{{ querystring_key }}"  to  data-el-querystring-key="{{ querystring_key }}"
