### ISSUE TITLE
django-el-pagination return all objects to the frontend or...?

### ISSUE THREAD

**Issue by adriancarayol** [shtalinberg/django-el-pagination#61]
I have a question about how django pagination works:

If I have 10 million objects in the database, returns the 10 million to "frontend" or is it asking the server bit by bit?

Thanks!

**Comment by shtalinberg** [comment]
You can set setting EL_PAGINATION_PER_PAGE
See all list of settings: 
http://django-el-pagination.readthedocs.io/en/latest/customization.html#settings
to DB use query like
`SELECT ••• FROM ...  DESC LIMIT 8 OFFSET 10`
