### ISSUE TITLE
install not working in 1.9  1.10

### ISSUE THREAD

**Issue by allox** [shtalinberg/django-el-pagination#62]
Installation instructions seem to be outdated and does not work for django 1.9, 1.10
That context processor does not exist anymore, and the handling of the 'request' has changed.

**Comment by shtalinberg** [comment]
all work fine with django 1.9, 1.10  and build tests with django 1.9, 1.10 passing ..
Do you have a problem ?

**Comment by allox** [comment]
hi @shtalinberg 
django.core.context_processors.request (as found in http://django-el-pagination.readthedocs.io/en/latest/start.html ) is deprecated , doesnt need to be included anymore.  
Also the render_to_response is deprecated (views.py line 106) , should be render().

**Comment by shtalinberg** [comment]
which version of  django-el-pagination are you using?

**Comment by shtalinberg** [comment]
way django.core.context_processors.request is deprecated? you can show it in the django release notes ?

**Comment by allox** [comment]
ok,  you're probably right about the self.render_to_response(context). I replaced them because I got an error, but perhaps that was not needed. 

right, it was not really deprecated; built-in template context processors have been moved to django.template.context_processors.  https://docs.djangoproject.com/en/1.10/releases/1.8/#django-core-context-processors
http://stackoverflow.com/questions/38709985/where-has-django-core-context-processors-request-gone-in-django-1-10/38710192

**Comment by pmarais** [comment]
I have added `'django.template.context_processors.request',` line to my `context_processors`, and that seemed to do the trick.

You should be able to add this in your `settings.py` after your `TEMPLATES` are declared:

```
TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.template.context_processors.request'')
```

Although I suggest just adding it to the `context_processors` manually like so:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                '...',
                '...',
                '...',
                '...',
                'django.template.context_processors.request', ## For EL-pagination
            ],
        },
    },
]
```

**Comment by shtalinberg** [comment]
I change docs for it
