### ISSUE TITLE
can we get different EL_PAGINATION_PER_PAGE for different views

### ISSUE THREAD

**Issue by jywu90** [shtalinberg/django-el-pagination#67]
For different listviews, can we have different EL_PAGINATION_PER_PAGE? Say 10 for one view, and 5 for another?

**Comment by shtalinberg** [comment]
The number of paginated entries is taken from settings, but you can override the default locally, e.g.:

`{% paginate 20 entries %}`

See http://django-el-pagination.readthedocs.io/en/latest/templatetags_reference.html#templatetags-reference

**Comment by shtalinberg** [comment]
Can close this issue ?

**Comment by mjrulesamrat** [comment]
`{% paginate 20 entries %}` Does the trick.

Ticket can be closed.
