### ISSUE TITLE
How do I use paginate nested variables?

### ISSUE THREAD

**Issue by amitlzkpa** [shtalinberg/django-el-pagination#7]
Trying to implement the following:
<code>              {% load el_pagination_tags %}</code>
<code>              {% paginate qaSet.items as questionSet %}</code>
<code>             {% for question, answerSet in questionSet %}</code>
<code>                            ...</code>
<code>              {% endfor %}</code>
<code>              {% show_pages %}</code>

It gives me the following error
<code>'dict_items' object is not subscriptable</code>

Thanks!

**Comment by shtalinberg** [comment]
Please, add more traceback information

**Comment by shtalinberg** [comment]
no reply :(

**Comment by albardn2** [comment]
I am having the same issue , can anyone help

**Comment by zaidbardan** [comment]
Can someone answer me

**Comment by reema1994** [comment]
Any solution?

**Comment by albardn2** [comment]
There are 2 solutions:

1) use diango rest API

2) make a new app called apis, and write views specifically for the nested variables
