### ISSUE TITLE
[Need Help] How to keep "el-pagination.js" up to date?

### ISSUE THREAD

**Issue by ravinimmi** [shtalinberg/django-el-pagination#73]
For endless scrolling i need to include **el-pagination.js** in my html file. 
So i copied this file from my virtualenv site packages and pasted in templates directory for my project and scrolling is working fine. 
Is this correct way to reference this javascript file in my project? 
What should I do to keep this file updated with the latest version of **django-el-pagination**?

**Comment by shtalinberg** [comment]
just
`<script src="{% static "el-pagination/js/el-pagination-endless.js" %}"></script>`
