### ISSUE TITLE
Where should I put a css or js import ?

### ISSUE THREAD

**Issue by rightx2** [shtalinberg/django-el-pagination#77]
I have list of post where each post should be affected by some `css` or `js` files.
Let say these script files are: `bootstrap-toggle.css` and `bootstrap-toggle.js`.

I wonder where  I should put `<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">` or `<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>`...

`my_list.html`
```
{% extends "skeleton/base.html" %}

{% load el_pagination_tags %}
 

{% block custom_stylesheet %}
{% endblock %}


{% block content %}
    {% include page_template %}
{% endblock %}



{% block custom_js %}
    <script src="{% static 'el-pagination/js/el-pagination.js' %}"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollMargin: 50
        });
    </script>
{% endblock %}

```

and

`my_list_page.html`

```
{% load el_pagination_tags %}


{% lazy_paginate posts %}

<div class="panel-group" id="accordion">
  {% for post in posts %}
    <div class="panel panel-info" data-pk="{{ post.pk }}">
      <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" data-target="#collapse{{post.pk}}">
        <h4 class="panel-title accordion-toggle" style="padding-bottom:5px;">
             {{ post.title }} {% if post.cliencomment_set.count > 0 %} [{{ post.cliencomment_set.count }}] {% endif %}
        </h4>
       </div>
    </div>
  {% endfor %}
</div>

{% show_more %}

```

Where should I put those so that  these script also could apply to newly ajax-loaded elements?

**Comment by int-ua** [comment]
It's not a question of where to put tags, it's about using jQuery correctly, [read `on()` docs](http://api.jquery.com/on/). In my case it's

    $('#some_wrapper').on('change', 'input.toggle-something', function () {
