### ISSUE TITLE
When user click next page if it will extract all items from database?

### ISSUE THREAD

**Issue by chengshuyi** [shtalinberg/django-el-pagination#81]
I have heard that `django-el-pagination` will only extract 10 items from database rather than all,if you set `EL_PAGINATION_PER_PAGE` to be 10. However,my project may give a opposite view.

#### Below is my code to extract items from db by for-loop.

```
for scoreDoc in scoreDocs:
        doc = searcher.doc(scoreDoc.doc)
        _id=str(doc.get("id"))
        print _id                                                         # print id
        sql='select * from webpage where id=%s'    #extract item from db by id.

        with conn.cursor() as cursor:
            cursor.execute(sql,(_id))
            rst=cursor.fetchone()
   
       ret['search_list'].append({'title':rst['title'],'url':rst['url']})
conn.close()
return render(request,'tjut/result.html',{'search_list':ret['search_list']})
```

1. Suppose that 50 items would be extracted and the number of a page is equal to 10.
2. Beginning,totally 50 id is printed in console.   [Why not 10?]
3. Click next page,still 50 id is printed in console. [Why not 10?]

Thanks for any comment.

**Comment by int-ua** [comment]
This looks wrong on many levels. Are you using Django? Why do you use raw SQL?

**Comment by shtalinberg** [comment]
@int-ua rights, use the django style in views/templates and read the documentation

**Comment by shtalinberg** [comment]
It's a not bug
