### ISSUE TITLE
Not compatible with jQuery 3.x

### ISSUE THREAD

**Issue by michelts** [shtalinberg/django-el-pagination#92]
The el-pagination code uses **.error** callback method, deprecated and removed in jQuery 3.x. We should use **.fail** instead:

http://api.jquery.com/jQuery.get/
(Take a look at the deprecation notice)

I didn't dig too much to see if there is any other problem with jQuery 3.x, anyway, to fix the problem, it can be better to create test environment variants for different jquery versions.

**Comment by SebCorbin** [comment]
A way to bypass these errors could be to use https://github.com/jquery/jquery-migrate

**Comment by toptalo** [comment]
Hi, here is my try #102

**Comment by shtalinberg** [comment]
@michelts, it's resolve this issue?

**Comment by michelts** [comment]
@shtalinberg Yes ;) You can close the ticket.

Anyway, I would suggest to have a tox configuration to variate the jquery version used in the base template of the tests project (instead of use http://code.jquery.com/jquery-latest.min.js directly).
