### ISSUE TITLE
Add ability to check page is_previous or is_next when iterate over pages

### ISSUE THREAD

**Issue by toptalo** [shtalinberg/django-el-pagination#96]
Thats now:
```
{% for page in pages %}
    {# display page link #}
    {{ page }}

    {# the page url (beginning with "?") #}
    {{ page.url }}

    {# the page path #}
    {{ page.path }}

    {# the page number #}
    {{ page.number }}

    {# a string representing the page (commonly the page number) #}
    {{ page.label }}

    {# check if the page is the current one #}
    {{ page.is_current }}

    {# check if the page is the first one #}
    {{ page.is_first }}

    {# check if the page is the last one #}
    {{ page.is_last }}
{% endfor %}
```

I need to customize links to previous and next pages, but for some reason there are no ability to check this pages.

`{{ page.is_previous }}` and `{{ page.is_next }}` may help in my situation

**Comment by toptalo** [comment]
I'm really need this feature asap

**Comment by toptalo** [comment]
Up

**Comment by shtalinberg** [comment]
Hi, 
I'll try to look and make the release before Monday

**Comment by toptalo** [comment]
Hi, it will be great!

**Comment by toptalo** [comment]
Hello! how's it going?

**Comment by toptalo** [comment]
Hello again! I still need this feature 🙄

**Comment by shtalinberg** [comment]
Hi,
I want bump 3.2.0
Please add documentation and tests for this futures

**Comment by toptalo** [comment]
Hello!
Can't run tests on my local machine. Have problem with Selenium WebDriver.
```python
WebDriverException: Message: Can't load the profile. Profile Dir: /var/folders/cq/7vn3qdrd11gchbl0gz0gzv3w0000gp/T/tmpBbfCOg If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

I make commit (toptalo/django-el-pagination@573f97a) to my fork with some documentation changes.

Maybe I can make PR with doc changes only?

**Comment by toptalo** [comment]
Oh. I see you already add this

**Comment by shtalinberg** [comment]
You can make PR,  all PRs automatic run tests via Travis CI before merge and you can see results https://travis-ci.org/shtalinberg/django-el-pagination and add changes to PR

**Comment by toptalo** [comment]
I see You already added documentation and tests for the futures. So we can close this issue.

I've already updated the package in my project and all works! Thanks a lot!

**Comment by shtalinberg** [comment]
Need update and add tests for this future, now tests does not exist for this future. 
I'm update only documentation.

**Comment by toptalo** [comment]
Okay I'll Try

**Comment by shtalinberg** [comment]
Great! :+1:
